rails:
  build: .
  tty: true
  stdin_open: true
  mem_limit: 384m
  environment:
    DISABLE_SPRING: "1"
  ports:
    - "3000:3000"
  volumes:
    - ".:/usr/src/app"
  links:
    - "mysql"

mysql:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: "passwd"
